# ==============================================================
#  LA SECTASIR
# ==============================================================

# ELIMINA o comenta esta línea:
# remote_theme: cotes2020/jekyll-theme-chirpy

# Y AÑADE esta línea en su lugar:
theme: jekyll-theme-chirpy

# Información del sitio
lang: es-ES
timezone: Europe/Madrid

# Información básica
title: La SectASIR
tagline: Administración de Sistemas Informáticos y Redes
description: >-
  Blog técnico sobre administración de sistemas, redes, 
  seguridad informática y tecnologías de infraestructura.

# URL del sitio (cámbialo por tu URL real)
url: "https://tu-usuario.github.io"

# GitHub username
github:
  username: tu-usuario

# Información del autor
social:
  name: La SectASIR
  email: contacto@lasectasir.com
  links:
    - https://github.com/tu-usuario
    - https://twitter.com/lasectasir
    - https://www.linkedin.com/in/tu-perfil

# Avatar (imagen de perfil)
avatar: /assets/img/avatar.jpg

# Modo del tema (light o dark)
theme_mode: # [light | dark]

# Tabla de contenidos en las publicaciones
toc: true

# Comentarios (opcional - puedes configurarlo después)
comments:
  active: # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # disqus:
  #   shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname

# Paginación
paginate: 10

# Configuración de Markdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Collections
collections:
  tabs:
    output: true
    sort_by: order

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-archives

# Jekyll Archives
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# Exclude archivos del build
exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json
  - deploy.sh
  - Gemfile
  - Gemfile.lock
  - vendor

# Configuración de Sass
sass:
  style: compressed

# Compresión HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]
